# Generated by Django 4.2.5 on 2023-10-05 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_details',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=60, null=True)),
                ('age', models.CharField(max_length=60, null=True)),
                ('hypertension', models.TextField(max_length=60, null=True)),
                ('heart', models.CharField(max_length=60, null=True)),
                ('married', models.CharField(max_length=60, null=True)),
                ('work', models.CharField(max_length=60, null=True)),
                ('residence', models.CharField(max_length=60, null=True)),
                ('bmi', models.TextField(max_length=60, null=True)),
                ('glucose', models.TextField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'predict_detail',
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(max_length=50, null=True)),
                ('contact', models.TextField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.TextField(max_length=8, null=True)),
                ('file', models.FileField(null=True, upload_to='images')),
                ('user_status', models.TextField(default='pending', max_length=30, null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=20)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
