# Generated by Django 4.2.5 on 2024-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='logistic',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logistic',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
    ]
