# Generated by Django 4.2.5 on 2024-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0002_logistic_confusion_matrix_logistic_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ada_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ada_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ada_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anm_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='anm_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anm_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ann_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ann_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ann_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dt_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dt_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dt_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='knn_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='knn_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='knn_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='svm_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='svm_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='svm_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xg_algo',
            name='Confusion_matrix',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='xg_algo',
            name='Sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xg_algo',
            name='Specificity',
            field=models.FloatField(default=0.0),
        ),
    ]
